### PR TITLE
[ux] User notification #40 #45

### LINKED ISSUE #40: [ux] Show error if token validation on openwisp-radius API fails
If the token validation of openwisp-radius fails (because organization uuid and secret have not been configured correctly) the operations (login, registration, etc) should fail with an error message.

We should also support the case in which the openwisp-radius API is returning a 500 internal server error or not responding (use mocking to write tests for this case).

PS: it seems that if the openwisp-radius is unavailable, an error message is correctly returned, but if the API is not replying (for example, if you drop an ipdb.set_trace() in the python code, preventing the API to respond) the react app acts like if the API has responded, while it should wait a bit and then timeout.

### LINKED ISSUE #45: [UI] Integrate react-toast-notifications and show notifications for events
Integrate [react-toast-notifications](https://www.npmjs.com/package/react-toast-notifications) with the app. Or propose any better package to show notifications to the user.
Show toast notifications to user for success and error events in all the pages including Login, Registration and Status page.

### PR DESCRIPTION
**Pull request by nikitaermishin**
This is a PR for commit which adds `react-toastify` library to make UX better. Changes:
 - adds `react-toastify` in `package.json`
 - Connects `react-toastify` in `login`, `password-confirm`, `password-reset`, `registration`, `status` pages:
    - Updates tests to check if toast function calls and added console error existance check
    - Updates `index.js` to add callback param to call function after redirect
    - Updates main files to add toast function calls on `axios` response
    - Adds new error and success messages to `client/constants/index.js`

#### Notes 
 - check my code-based review for notes
 - feel free to ask for any changes

Fixes #40, fixes #45

### CODE REVIEW

File: client/constants/index.js [hunk 1]
```diff
@@ -1,6 +1,12 @@
 export const confirmApiUrl = "/api/v1/{orgSlug}/account/password/reset/confirm";
+export const genericError = "Error occurred!";
 export const loginApiUrl = "/api/v1/{orgSlug}/account/token";
+export const loginError = "Login error occurred.";
+export const loginSuccess = "Login success.";
+export const logoutSuccess = "Logout.";
 export const passwordConfirmError = "The two password fields didn't match.";
 export const registerApiUrl = "/api/v1/{orgSlug}/account/";
+export const registerError = "Registration error.";
+export const registerSuccess = "Registration success";
```
Comment (nikitaermishin) [inline client/constants/index.js]: Is it correct to store error and success messages here (passwordConfirmError was here initially) or we should store them in `org-configuration`, so we can add localization, or maybe somewhere else?

File: client/components/login/login.test.js [hunk 2]
```diff
@@ -64,10 +65,20 @@ describe("<Login /> rendering", () => {
...
+    lastConsoleOutuput = null;
+    console.error = (data) => {
+      lastConsoleOutuput = data;
+    };
     props = createTestProps();
     wrapper = shallow(<Login {...props} />);
   });
+  afterEach(() => {
+    console.error = originalError;
+  });
```
Comment (nikitaermishin) [inline client/components/login/login.test.js]: This code helps in `console.error`s handling (`login.js` generates them among with `toast.error` on error):
 - doesn't throw an error to console, so doesn't fail tests
 - adds `lastConsoleOutput` to check if the information about error actually exists during testing

File: client/components/login/login.test.js [hunk 3]
```diff
@@ -92,20 +103,72 @@ describe("<Login /> interactions", () => {
...
+      })
+      .mockImplementationOnce(() => {
+        return Promise.reject({
+          response: {
+            data: {}
+          },
+          status: 504,
+          statusText: "Gateway Timeout"
+        });
+      })
```
Comment (nikitaermishin) [inline client/components/login/login.test.js]: - Added this lines to test `500 error` and `server unvailable`
- Added this data in `Promise.reject` arguments for `console.error` to show error correctly

File: client/components/password-confirm/password-confirm.js [hunk 4]
```diff
@@ -62,17 +64,25 @@ export default class PasswordConfirm extends React.Component {
           errors: {},
           success: response.data.detail,
         });
+        toast.success(response.data.detail);
       })
       .catch(error => {
         const {data} = error.response;
-
+
```
Comment (nikitaermishin) [inline client/components/password-confirm/password-confirm.js]: My bad, I will fix on the next commit version after your review

File: client/components/login/index.js [hunk 5]
```diff
@@ -15,8 +15,9 @@ const mapStateToProps = state => {
 
 const mapDispatchToProps = dispatch => {
   return {
-    authenticate: status => {
+    authenticate: (status, callback) => {
       dispatch({type: SET_AUTHENTICATION_STATUS, payload: status});
+      setTimeout(callback, 0);
```
Comment (nikitaermishin) [inline client/components/login/index.js]: Uses to asyncronously call `callback` function after change of `SET_AUTHENTICATION_STATUS`. This helps to appear `toast` on the page after redirect.

File: client/components/login/login.js [hunk 6]
```diff
@@ -67,17 +69,27 @@ export default class Login extends React.Component {
...
+          ':',
+          errorText
+        );
         this.setState({
           errors: {
             ...errors,
-            ...(data.non_field_errors
-              ? {nonField: data.non_field_errors[0]}
-              : {nonField: ""}),
-            ...(data.detail ? {nonField: data.detail} : {}),
```
Comment (nikitaermishin) [inline client/components/login/login.js]: Now this information displays in `toast`s, no need in it here anymore

**Comment by Vivekrajput20** [comment]
@nemesisdesign yes I intentionally  returned that when `error.response` was undefined. I was not sure what to return in such circumstance.

**Comment by nikitaermishin** [comment]
@nemesisdesign @Vivekrajput20 I added `error.response` according to data provided by real test with `browser developer tools -> network`

File: server/utils/log-internal-error.js [hunk 7]
```diff
@@ -0,0 +1,7 @@
+const logInternalError = (error) => {
+  const errorText = `Operation failed!\n${
+    error.config.method} to ${error.config.url}\ncode: ${
+    error.code}`;
+  console.log(errorText);
+};
+export default logInternalError;
```
Comment (atb00ker) [inline server/utils/log-internal-error.js]: Eh, endline. :sweat_smile:

File: client/utils/log-error.js [hunk 8]
```diff
@@ -0,0 +1,10 @@
+const logError = (error, errorText = "") => {
+  console.error(
+    'Status',
+    error.response.status,
+    error.response.statusText,
+    ':',
+    errorText
+  );
+};
+export default logError;
```
Comment (atb00ker) [inline client/utils/log-error.js]: Eh, endline. :sweat_smile:

File: client/utils/get-error-text.js [hunk 9]
```diff
@@ -0,0 +1,10 @@
+const getErrorText = (error, fallbackVal = "") => {
+  const {data} = error.response;
+  // eslint-disable-next-line no-nested-ternary
+  return data.detail
+    ? data.detail
+    : data.non_field_errors
+    ? data.non_field_errors[0]
+    : fallbackVal;
+};
+export default getErrorText;
```
Comment (atb00ker) [inline client/utils/get-error-text.js]: Eh, endline. :sweat_smile:

File: server/utils/log-internal-error.js (hunk 7 above)
Comment (nikitaermishin) [reply server/utils/log-internal-error.js]: Hmm, shouldn't `npm run lint` check for it?

Comment (nikitaermishin) [reply server/utils/log-internal-error.js]: Hmm, shouldn't `npm run lint` check for it?

Comment (atb00ker) [reply server/utils/log-internal-error.js]: I am not sure, this is a new repository, I've not even installed it yet! :sweat_smile: 
If not npm something needs to detect and fail travis for it, most likely it would be `openwisp-utils chec[qa]` script that needs to be added here!

Comment (nikitaermishin) [reply server/utils/log-internal-error.js]: I've added `eof-last` rule to `eslintrc.json`

**Comment by Vivekrajput20** [comment]
@nikitaermishin I recently merged another branch which adds password change component. Can you please rebase your work and add notifications to that component as well?
Thanks

**Comment by nikitaermishin** [comment]
@Vivekrajput20 Rebased and added notifications, as you've asked

File: client/components/password-change/password-change.js [hunk 10]
```diff
@@ -45,12 +49,16 @@ export default class PasswordChange extends React.Component {
         newPassword1,
         newPassword2,
       }),
-    }).then(() => {
+    }).then((response) => {
+      setTimeout(() => toast.success(response.data.detail), 0);
```
Comment (Vivekrajput20) [inline client/components/password-change/password-change.js]: Why are you using setTimeout and not calling it directly?

Comment (nikitaermishin) [reply client/components/password-change/password-change.js]: @Vivekrajput20 I am using setTimeout 0 because it calls toast after some amount of time (like 1 tick), and during this time our url will be changed (check next line), so our toast will be displayed on the new page.

**Comment by Vivekrajput20** [comment]
@nikitaermishin  I see `Remember to render the ToastContainer once in your application tree. If you can't figure out where to put it, rendering it in the application root would be the best bet.` in the documentation. You are rendering ToastContainer in every component. I think you should render it only once in `client/index.js` and then you will not require to use setTimeout to render popup in the next page.

**Comment by nikitaermishin** [comment]
@Vivekrajput20 Made a new version of commit, removed all ToastContainer's and added one to `client/index.js`. Please check some code in my review.

File: client/components/status/status.js [hunk 11]
```diff
@@ -29,10 +32,18 @@ export default class Status extends React.Component {
...
+          });
+          logError(response, '"control:Auth-Type" !== "Accept"');
         }
       })
-      .catch(() => {
+      .catch((error) => {
         logout(cookies, orgSlug);
+        toast.error(loginError, {
+          onOpen: () => toast.dismiss(mainToastId),
+        });
```
Comment (nikitaermishin) [inline client/components/status/status.js]: Added this code, so success message will automatically be closed when the token check error occurred

**Comment by nikitaermishin** [comment]
@Vivekrajput20 added `.*.swp` and `.*.swo` to gitignore. Also made some minor corrections.
