### PR TITLE
[fix] Use calling_station_id instead of macaddr for MAC filtering #914

### LINKED ISSUE #914: Status component uses incorrect query param for session lookup
**Describe the bug**
The Status component in the client currently checks for an active session by filtering with the `macaddr` query parameter. However, the OpenWISP RADIUS API endpoint does not support filtering by `macaddr`; it expects `calling_station_id` as the query param for MAC address-based filtering.

**Relevant code:**
-[ `client/components/status/status.js` (uses `macaddr` as query param)](https://github.com/openwisp/openwisp-wifi-login-pages/blob/e1ef7e0f7ad910faf51ff04c8ec878a865835e90/client/components/status/status.js#L217-L231)
- [The RADIUS API (`openwisp_radius/api/views.py`) expects `calling_station_id` for MAC address filtering.](https://github.com/openwisp/openwisp-radius/blob/4d9d85195624b60f157339e8884ac45539918f30/openwisp_radius/api/views.py#L808-L848)

**Steps To Reproduce**
1. Attempt to retrieve radius sessions for a user with a specific MAC address.
2. Observe that the frontend sends a `macaddr` query param to the API.
3. The API does not filter sessions as expected because it does not recognize `macaddr`.

**Expected behavior**
The frontend should use the `calling_station_id` query parameter when requesting sessions by MAC address, matching the OpenWISP RADIUS API's expectations.

### PR DESCRIPTION
**Pull request by pranshustuff**
## Checklist

- [x] I have read the [OpenWISP Contributing Guidelines](http://openwisp.io/docs/developer/contributing.html).
- [x] I have manually tested the changes proposed in this pull request.
- [x] I have written new test cases for new code and/or updated existing tests for changes to existing code.
- [ ] I have updated the documentation.

## Reference to Existing Issue

Closes #914 

## Description of Changes

Status component used param `macaddr` to filter
users by MAC address but Radius session uses the
param `calling_station_id`. Caused it to return all sessions instead of filtering properly.

Changed params for getUserActiveRadiusSessions(params) from `{ macaddr }` to `{ calling_station_id: macaddr }`

### CODE REVIEW

File: client/components/status/status.js [hunk 1]
```diff
@@ -218,7 +218,7 @@ export default class Status extends React.Component {
 
       const macaddr = cookies.get(`${orgSlug}_macaddr`);
       if (macaddr) {
-        const params = {macaddr};
+        const params = {calling_station_id: macaddr};
```
Comment (nemesifier) [inline client/components/status/status.js:221]: There's at least one more occurrence of `const params = {macaddr}` in `handleLogout`.

**Review by nemesifier — CHANGES_REQUESTED** [review]
Look at status.test.js, we have several tests in which we check that `getUserActiveRadiusSessions`. We can add one test which verifies it gets called with the right param.

File: client/components/status/status.js (hunk 1 above)
Comment (pranshustuff) [reply client/components/status/status.js:221]: Fixed!
