### PR TITLE
[fix] Relay querystring in sync auth mode #904

### LINKED ISSUE #904: [bug] Sync auth: querystring params not relayed
Follow up of #864.

It seems that when using the sync auth mode, querystring parameters usually added by captive portal softwares are not relayed to status page after loggin in. These querystring parameters sometimes contain reply messages sent to the captive portal in RADIUS reply messages, which we show to users.

### PR DESCRIPTION
**Pull request by pandafy**
## Checklist

- [x] I have read the [OpenWISP Contributing Guidelines](http://openwisp.io/docs/developer/contributing.html).
- [ ] I have manually tested the changes proposed in this pull request.
- [ ] I have written new test cases for new code and/or updated existing tests for changes to existing code.
- [ ] I have updated the documentation.

## Reference to Existing Issue

Closes #904

### CODE REVIEW

File: client/components/status/status.js [hunk 1]
```diff
@@ -577,11 +589,13 @@ export default class Status extends React.Component {
...
-      if (reply || title.indexOf("404") >= 0) {
+      if (title.indexOf("404") >= 0) {
         logout(cookies, orgSlug);
-        toast.error(reply, {
-          onOpen: () => toast.dismiss(mainToastId),
-        });
+      }
+      if (reply && !toast.isActive(mainToastId)) {
+        /* disable ttag */
+        toast.error(gettext(reply));
```
Comment (pandafy) [inline client/components/status/status.js:613]: **ATTENTION REQUIRED**

I have changed the code to give more preference to the toast message created by postMessage handler (authMessage / authError). This prevents double error toast for the same reply.
